---
  - src: git@github.com:netology-code/mnt-homeworks-ansible.git
    scm: git
    version: 2.0.0
    name: elastic
  - src: git@github.com:OmegaM/kibana-role.git
    scm: git
    name: kibana
    version: 0.0.1
  - src: git@github.com:OmegaM/filebeat-role.git 
    scm: git
    name: filebeat
    version: 0.0.1
