---
all:
  hosts:
    el-instance:
      ansible_host: 51.250.1.10 
    k-instance:
      ansible_host: 51.250.10.173 
    f-instance:
      ansible_host: 51.250.7.78
  vars:
    ansible_connection: ssh
    ansible_user: omi
elasticsearch:
  hosts:
    el-instance:
kibana:
  hosts:
    k-instance:
filebeat:
  hosts:
    f-instance:

